apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exercise
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-exercise
  template:
    metadata:
      labels:
        app: prometheus-exercise
    spec:
      containers:
        - name: prometheus-exercise
          image: prom/prometheus
          ports:
            - containerPort: 9090
