apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-exercise
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-exercise
  endpoints:
    - port: "80"
